apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80  # Exposes port 80 for this service
      targetPort: 5000  # Maps to the container's port
  type: ClusterIP  # Internal access within the cluster
